endpoints:
  enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:8889/Cucule
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
logging:
  file: log/Cucule.log
  level:
    org:
      springframework: INFO
      hibernate: DEBUG
      mybatis: INFO
    com:
      cucule:
        dao: DEBUG
mybatis:
  configuration:
    map-underscore-to-camel-case: false
    default-fetch-size: 100
    default-statement-timeout: 30
